version: "3"
services:

  register-runner:
    image: gitlab/gitlab-runner:alpine
    networks:
     - git
    volumes:
      - 'config-runner:/etc/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock'
    env_file: .env
    command:
      - /bin/bash
      - -c
      - /usr/bin/gitlab-runner
      - register
      - --non-interactive
      - --url
      - "$GITLAB_URL"
      - --registration-token
      - "$RUNNER_TOKEN"
      - --executor
      - "docker"
      - --docker-image
      - alpine:latest
      - --description
      - "docker-runner"
      - --tag-list
      - "docker"
      - --run-untagged="true"
      - --locked="false"
      - --access-level="not_protected"

volumes:
  config:
  logs:
  data:
  config-runner:

networks:
  git: